from enum import Enum

class LevelUpEndpointEnum(Enum):
    user_addresses = 'user_addresses'
    qr_codes = 'qr_codes'
    merchants = 'merchants'
    customer = 'customer'
    registration = 'registration'
    campaigns = 'campaigns'
    users = 'users'
    campaign_unlockings = 'campaign_unlockings'
    loyalties = 'loyalties'
    legacy = 'legacy'
    claims = 'claims'
    icon = 'icon'
    locations = 'locations'
    credit_cards = 'credit_cards'
    loyalty = 'loyalty'
    access_tokens = 'access_tokens'
    codes = 'codes'
    passwords = 'passwords'
    one = '1'
    credit = 'credit'
    merchant_funded_credit = 'merchant_funded_credit'
    get_merchant_funded_gift_card_credit = 'get_merchant_funded_gift_card_credit'
    managed_locations = 'managed_locations'
    image = 'image'
    web_links = 'web_links'
    orders = 'orders'
    proposed_orders = 'proposed_orders'
    completed_orders = 'completed_orders'
    refund = 'refund'
    apps = 'apps'
    interstitial = 'interstitial'
    feedback = 'feedback'
    payment_method = 'payment_method'
    permissions_requests = 'permissions_requests'
    progress_adjustments = 'progress_adjustments'
    reward_summary = 'reward_summary'
    gift_card_value_additions = 'gift_card_value_additions'
    gift_card_value_orders = 'gift_card_value_orders'
    gift_card_value_removals = 'gift_card_value_removals'
    detached_refunds = 'detached_refunds'

